### ISSUE TITLE
poor IDE support due to macro usage

### ISSUE THREAD

**Issue by chernetsov** [storm-enroute/coroutines#13]
Such a method return type won't allow IntelliJ IDEA to highlight code correctly.

```
  def coroutine[T](f: Any): Any = macro Coroutine.synthesize
```

Seems that a special plugin for IDEA needs to be built:
http://blog.jetbrains.com/scala/2015/10/14/intellij-api-to-build-scala-macros-support/

**Comment by axel22** [comment]
I didn't play with it, but we could probably replace `Any` with `R` and `Coroutine.Frame[Y, R]`, in that order.
What would you suggest?

**Comment by axel22** [comment]
I can replace the first `Any` with `R`. The second `Any` would need to become `Coroutine[Y, R]`, but that doesn't play nicely with type inference for `Y` and `R`, and it would not buy much, since `Coroutine[Y, R]` does not have any interesting user-facing methods.

If you have any idea how to refine the return type, please propose it. Closing for now.
