### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by velvia** [storm-enroute/coroutines#8]
Hey guys,

Awesome project!   There is no mention in the docs about concurrency, what is the story here?  When I launch a coroutine, where does it run?

How about performance, compared to traditional JVM method invocations?

Thanks.

**Comment by axel22** [comment]
Thanks!

Good point - concurrency is a topic we need to discuss. I'm currently working on adding more information to the docs. Expect an update soon.

Quick answer: the concurrency story is simple - there is no concurrency whatsoever involved. This is because any kind of concurrency (i.e. synchronization between separate threads) makes things slow, and is unnecessary.

When a coroutine instance is resumed, it happens on the caller thread as a normal method call, with a few housekeeping operations.

At the same time, coroutines can be (and are meant to, among other things) to be used to implement concurrency primitives and frameworks. Thing Erlang-style actors without top-level-only receives, or Oz-style single-assignment variables.

About performance: I have a TODO item to publish the benchmarks. Roughly, expect the following:
- launching a new coroutine instance (`call`) - relatively fast, but requires a few object allocations - faster than starting a future
- resuming an existing coroutine instance (`resume`) - fast, no allocs, slightly slower than invoking a method, and much faster than starting a future, and a LOT faster than starting a thread
- invoking another coroutine from within a coroutine (not covered in the docs yet) - fast, no allocs, slightly slower than invoking a method, and much faster than starting a future, and a LOT faster than starting a thread

**Comment by axel22** [comment]
I added a [FAQ document](http://storm-enroute.com/coroutines/docs/faq/) to explain this better.

**Comment by axel22** [comment]
Closing for now.

**Comment by velvia** [comment]
Thanks for the insights.  I’ll think about possibly replacing some Futures-based APIs, especially ones involving iteration over data, with this.  It is possible that the coroutines might still use other Futures APIs to bring in data though since so many Scala APIs use Futures.   I’m thinking that if this was combined with Go-style channels for I/O, that would be a powerful combination.
